#!/bin/bash

# Adds libs from requirements.txt to every docker container

containers=( airflow-airflow-webserver-1 airflow-airflow-worker-1 airflow-airflow-triggerer-1 airflow-airflow-scheduler-1 )

for container in "${containers[@]}"
do
    echo "Installing requirements.txt in $container"
    docker cp requirements.txt $container:/opt/airflow
    docker exec -it $container python -m pip install -r requirements.txt
done
